name: hdf5-iotest

# Controls when the action will run. 
#Triggers the workflow on push or pull requests.
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that
# can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        name: ["Ubuntu Latest GCC", "Ubuntu Latest GCC -- develop"]
        include:
          - name: "Ubuntu Latest GCC"
            artifact: "Linux.tar.xz"
            os: ubuntu-latest
            hdf5: "release"
          - name: "Ubuntu Latest GCC -- develop"
            artifact: "Linux.tar.xz"
            os: ubuntu-latest
            hdf5: "develop"

    name: ${{ matrix.name }}
    # The type of runner that the job will run on.
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    # Steps represent a sequence of tasks that will be executed 
    # as part of the job.
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Update repository code
      run: |
        sudo apt-get update
        sudo apt-get install uuid-dev

    - name: Install Dependencies (Linux--HDF5-release)
      if: matrix.hdf5 == 'release'
      run: |
        sudo apt-get install -qq mpich
        sudo apt-get install -qq libhdf5-mpich-dev
        # Set env vars
        echo "CC=mpicc" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/include/hdf5/mpich" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/mpich" >> $GITHUB_ENV

    - name: Install Dependencies (Linux--HDF5-develop)
      if: matrix.hdf5 == 'develop'
      run: |
        # Use the newest stable gcc compiler
        sudo apt-get install automake autoconf libtool libtool-bin
        sudo apt-get install -qq mpich
        echo "CC=mpicc" >> $GITHUB_ENV

        ##################################
        # INSTALL HDF5 FROM SOURCE
        ##################################
        git clone https://github.com/HDFGroup/hdf5.git
        export HOME_DIR=$(echo ~)
        cd hdf5
        ./autogen.sh
        ./configure --enable-build-mode=debug --without-szlib --disable-fortran --disable-hl \
        --disable-tests --disable-tools \
        --prefix=$HOME_DIR/hdf5 \
        --enable-parallel
        make -j 8 install
        mydir="$PWD"
        echo "HDF5_DIR=$mydir/hdf5/hdf5" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$HOME_DIR/hdf5/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L$HOME_DIR/hdf5/lib" >> $GITHUB_ENV

##################################
# CONFIGURE (Autotools)
##################################

    - name: configure hdf5-iotest
      run: |
        ./autogen.sh
        mkdir build; cd build
        echo "void main(void){}" > junk.c
        ls $HDF5_DIR/bin/h5pcc
        $HDF5_DIR/bin/h5pcc junk.c
        CC=$HDF5_DIR/bin/h5pcc ../configure --prefix=$GITHUB_WORKSPACE/build
      shell: bash

##################################
# BUILD HDF5-iotest
##################################

    - name: test hdf5-iotest
      run: |
        cd build
        make 
        make install
      shell: bash
